### PR TITLE
add routes section to the readme

### PR DESCRIPTION
**Pull request by PhillippOhlandt**
yes you can merge, I'll create a PR for every section now :)

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
:koala: where are you? 

Do your :octopus: work :D

**Comment by GwendolenLynch** [comment]
In Australia… 10 hours ahead of you.

**Comment by PhillippOhlandt** [comment]
Uh then, good night :P Or already good morning? .P

**Comment by PhillippOhlandt** [comment]
Ah and can you come back with a kangaroo for me? :)

**Comment by GwendolenLynch** [comment]
> Uh then, good night :P Or already good morning? .P

Well that was merged at 04:00 here, so good morning is probably right :grin: 

> Ah and can you come back with a kangaroo for me? :)

Those things are vicious… but tasty!

**Comment by PhillippOhlandt** [comment]
Nah I want it as pet! :P

**Pull request merged**
