### PR TITLE
Even Listeners

### PR DESCRIPTION
**Pull request by PhillippOhlandt**
I open it now just to get the green square for today :P Will finish it commit by commit by the end of tomorrow. Will let you know then =)

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
So, the listeners itself are in but with no real functionality to keep it clean. I referenced an example in the docs.

**Comment by PhillippOhlandt** [comment]
nah wait, found an issue

**Comment by PhillippOhlandt** [comment]
here we go

**Comment by GwendolenLynch** [comment]
So are the `*_DELETE` events working in 2.2 at the moment?

**Comment by PhillippOhlandt** [comment]
Yep their are working. You don't get all record information but the ID and a few things from the record itself.

**Comment by GwendolenLynch** [comment]
:+1:

**Pull request merged**
